version: '3'
services:
  web:
    container_name: api
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    networks:
      - postgres
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/postgres
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: >
      bash -c "pip install -r ./requirements.txt;
              
              echo -e '\n\n--------- DATABASE MIGRATION ---------';
              PYTHONPATH=. alembic upgrade head;
              echo -e '--------- END OF DATABASE MIGRATION ---------\n\n';

              flask run --host=0.0.0.0 --port=80;"
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"

  postgres:
    container_name: database
    image: postgres:10.12
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
       - ./pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: